### PR TITLE
Change impure tear

### PR DESCRIPTION
**Pull request by Prometheus0000**
This makes it not a meme item no one uses, but is still expensive. That can be revisited after people actually try it out in a released build if necessary.

### CODE REVIEW

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5978

**Comment by Rakdarian** [comment]
I support this

**Comment by Cleista** [comment]
This isn't a significant enough buff IMO, how about making it remove half of your warp over 50, prioritizing Temporary -> Normal -> Permanent?

**Comment by Prometheus0000** [comment]
It already prioritized like that. And let's wait and see if people use it before trying to buff it more, I'd like it to actually get merged, and not get rejected.

**Comment by Rakdarian** [comment]
I think a reason to incentivise automation of thaumcraft prior to osmiridium is a great idea, and this would help immensely for that

**Comment by Prometheus0000** [comment]
I also wanted to encourage people to get into other stuff (crops, BM) at least a little by putting items in the recipe.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
