### PR TITLE
Adds fake discord ping and voice channel join events

### PR DESCRIPTION
**Pull request by querns**
# Functionality

Adds warp events that play the Discord ping sound (50 warp) and Discord voice channel join sound (100 warp.) These events are rate limited to only play once a day.

# Additional Context

image

### CODE REVIEW

**Comment by mitchej123** [comment]
What's the license on the sound files?

**Comment by querns** [comment]
Ah hell, I forgot about licensing. Let me see if I can dig anything up about that. If it's not permitted then we can nuke this PR, it was only about a half hour of my time and I was only about 60% serious about it actually being added.

**Comment by Dream-Master** [comment]
> What's the license on the sound files?

thats what i asking myself this moment as well.

**Comment by Dream-Master** [comment]
> Ah hell, I forgot about licensing. Let me see if I can dig anything up about that. If it's not permitted then we can nuke this PR, it was only about a half hour of my time and I was only about 60% serious about it actually being added.

why not if the license allow it

**Comment by querns** [comment]
I can't find a clear answer on the Internet about whether or not it's a copyrighted sound. I have, however, found a video where a kid essentially recreates the sound from scratch inside of about a minute. https://www.youtube.com/watch?v=clUURA7RYxw . IANAL, but I think that there's no way to distinguish the actual sound from a recreation due to the fact that it's so simple. It's not like I dug into Discord's files to acquire the sound or anything.

Still, up to you guys. If this excuse is too flimsy, just close the PR. Shit happens; wear a helmet.

**Comment by brandyyn** [comment]
what about steam message noises and steam call sound

**Comment by querns** [comment]
The Steam notification noises are more complex than Discord's. Assuming my flimsy justification passes muster for the Discord ones, it likely won't for Steam's. Not gonna risk it.

**Comment by chochem** [comment]
not very immersive

**Comment by Alastors** [comment]
Neither is most of warp theory

I'm in favour if we can

**Review by mitchej123 — CHANGES_REQUESTED** [review]
Please move the sounds to their own subdirectory, and add your summary of the license -- fair use/easily reproducible/not copywriteable/etc.  I'm fine with it, just want it to be explicit.  Good after that.

**Comment by Dream-Master** [comment]
@querns

**Comment by mitchej123** [comment]
|| Also double the number of eggs alastor lays ||

**Comment by Alastors** [comment]
Wuuuhhhhhhhhh :fail:

**Comment by querns** [comment]
There. IANAL, but I hope that is enough disclaimer.

**Review by mitchej123 — APPROVED** [review]

**Pull request merged**
