### PR TITLE
Changed Tear and talisman textures

### PR DESCRIPTION
**Pull request by ghost**
I always thought the texture didn't correspond to a "tear" so I made another (imho better looking) texture that is a derivative of a ghast tear (It also glows, yay). The amulet colors were remade to match that change. A few rendering changes had to be done to render the tear nicely in hand. Thanks to TechnicianLP for that.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@jackowski626 are you add the impure tear too ? The new one ?

**Comment by Prometheus0000** [comment]
He did

**Comment by jackowski626** [comment]
Should the Warp Theory tab icon in the Thaumonomicon be static, like orginally, or animated?

**Comment by Dream-Master** [comment]
All Tabs are static

**Pull request merged**
