### PR TITLE
Massive refactor + add new warp effects

### PR DESCRIPTION
**Pull request by D-Cysteine**
Sorry, this is a massive PR. I've tested this myself, including on dedicated server, but would appreciate help with testing this more thoroughly (maybe on Zeta?). I'm sure that there are many bugs that I've missed. Also need help with testing effects with more than one player, especially the doppelgänger.

For an overview of the new warp effects, see:
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8611#issuecomment-958003423

Please also give any thoughts on balance on that issue!

Complete changelog below:
 * Massive refactor to make adding new warp effects much, much easier
    * Clean up code duplication by adding helper classes
    * Had IntelliJ reformat everything
 * I discovered that the 200 warp limit seems to be easily changeable. I moved it into a constant.
 * Improved existing warp effects
   * Chest scramble and acceleration warp effects are now considered global effects
   * Blink warp effect now has the effect reduced by 5% of the current value. This will make it wear off much faster if you've stacked it to a high level.
   * Minor bug fixes for friendly creeper: now starts with 100 HP (rather than just 100 max HP) and is no longer multi-leashable
   * Added support for multi-level warp effects. If you have a lot more warp than the minimum for the effect, you'll get a chance of a stronger warp effect.
     * Bats warp effect now has multiple levels:
       * 0: normal
       * 1: bats are on fire
       * 2: bats are on fire and have fire resistance
     * Blood warp effect now has multiple levels:
       * 0: normal
       * 1: blood is black
     * Livestock rain warp effect now has multiple levels:
       * 0: normal
       * 1: rains squid
       * 2: rains tainted animals (note that tainted sheep can spread taint, should they somehow survive the fall!)
     * Friendly creeper warp effect now has multiple levels:
       * 0: normal
       * 1: "friendly" creeper will explode, but does no damage
       * 2: same as 1, except the creeper is invisible for just long enough to get in range =)
 * Added new warp effects, which are all disabled by default:
   * Blaze fireball: after 2.5 seconds, player fires three blaze fireballs
   * Obsidian: places obsidian on top of the player's head, causing suffocation
   * Coin: spawns a Thaumcraft coin at the player
   * Countdown bomb: counts down from 10, then causes a creeper explosion at the player's location
   * Doppelganger: like passive creeper, but reflects all damage it suffers onto you
   * Ender pearl: throws an ender pearl
   * Endermen: spawns angry endermen at night. Multi-level; at level 1, the endermen have invisibility and strength 2.
   * Eye blink: player blinks a few times (blindness for 1 second)
   * Fake rain: spawns fake rain drops around you. Multi-level; at level 1, rains blood.
   * Fire bats: spawns Thaumcraft fire bats. Same message as regular bats. Multi-level; at level 1, bats can be explosive or devil.
   * Insomnia: player is unable to sleep for a few minutes
   * Inventory swap: does one of these two things at random:
     * Place the item in hand into inventory, leaving the hand empty
     * Swap two slots at random in inventory (excluding hotbar)
   * Junk: completely fills the hapless player's inventory with garbage
   * Lay eggs: player lays eggs at random intervals
   * Litmus paper: gives the player litmus paper, as a not-so-subtle warning about high warp. Can only occur once per 8 hours.
   * Mushrooms: plants mushrooms, converts grass and dirt to mycelium, and converts vanilla cows to mooshrooms
   * Phantoms: spawns some mobs that don't move, and vanish when looked at
   * Pumpkin: places a pumpkin onto the player's head (if no helmet)
   * Snow: places snow, converts water to ice, and spawns snow golems on snow or ice
   * Wand drain: drains a random amount of vis from wands in the player's inventory
   * Wither potion: gives the player 30 seconds of wither 3, hunger 3, and slowness 3
   * Fake low-pitched enderman anger sound
   * Fake wither spawn sound
 * /warptheory command has been greatly improved
   * Added additional commands: print (prints current warp effect levels) and purge (removes warp effects)

### CODE REVIEW

**Comment by D-Cysteine** [comment]
Oh, forgot to mention, all of the new effects are disabled and require 100 warp by default. We can change the defaults once we've come up with what warp levels they should have. Also, I'm attaching a zip file of a built jar and a config file with all effects enabled, in case anyone wants to help test or just try it out.

[test-files.zip](https://github.com/GTNewHorizons/WarpTheory/files/7463161/test-files.zip)

**Comment by D-Cysteine** [comment]
I've made the changes mentioned here:
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8611#issuecomment-958219440

Also made the new effects enabled by default, though they still all have warp level 100. Will need to adjust that once we have decided on new warp levels.

New test files:
[test-files.zip](https://github.com/GTNewHorizons/WarpTheory/files/7469076/test-files.zip)

Changelog:
 * Add two new warp effects:
   * Inventory Scramble: scrambles entire player inventory, excepting currently selected item
   * GregTech Fake Sound: multi-level; three GT fake sounds
     * Wrench
     * Machine out of power
     * Howler alarm (triggers 8x)
 * Made new warp effects default to enabled
 * A little clean-up

**Comment by Glease** [comment]
For massive refactor, it'd help greatly if you do all the reformatting in the first commit, and do actual work in later commits. This way we can just skim through the reformatting commit (which can be HUGE) first, then review the patch (always smaller) with greater care.

**Comment by D-Cysteine** [comment]
Yeah, that makes sense. Sorry I didn't do that this time.

**Comment by Glease** [comment]
No worries. We can do it next time.

**Comment by Dream-Master** [comment]
lets test this on zeta

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
