### PR TITLE
Add aspects to Warp Theory entities

### PR DESCRIPTION
**Pull request by D-Cysteine**

### CODE REVIEW

**Comment by Dream-Master** [comment]
Are this not controlled via Thaumcraft Mob Aspects mod ? We have a warp Theory config but only passive creeper is listed
[WarpTheory.zip](https://github.com/GTNewHorizons/WarpTheory/files/15097661/WarpTheory.zip)

**Comment by D-Cysteine** [comment]
> Are this not controlled via Thaumcraft Mob Aspects mod ? We have a warp Theory config but only passive creeper is listed [WarpTheory.zip](https://github.com/GTNewHorizons/WarpTheory/files/15097661/WarpTheory.zip)

Huh, thanks, I didn't know about that mod. It does look like most of the configs for mods don't actually have any aspects listed though, including Warp Theory, like you said:
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/241ef90cd75955e0d09e9d5ba502b35803d3a318/config/ThaumcraftMobAspects

I feel like it probably makes sense to have that mod handle mobs from mods that aren't aware of / don't depend on Thaumcraft, but for mods that do, like Warp Theory, it might be better to have the mod itself handle registering aspects. That way we can keep the aspect definitions in the same repo as the actual entity, and update them in the same PR.

**Comment by Dream-Master** [comment]
ok sure i just want to let you know.

**Comment by Alastors** [comment]
Yeah it'd be better to handle warp theory mobs in warp theory

**Review by Alastors — APPROVED** [review]

**Pull request merged**
